export interface FileNode {
  name: string
  path: string
  type: 'file' | 'dir'
  children?: FileNode[]
}

export interface SearchResult {
  path: string
  filename: string
  excerpt: string
  root: string
}

// Frontmatter fields from the memory file schema
export interface MemoryFileMeta {
  name: string
  type: 'feedback' | 'project' | 'user' | 'reference' | string
  projects: string | string[]
  created: string
  updated: string
  tags?: string[]
  status?: 'active' | 'archived' | 'superseded' | string
  supersedes?: string
  /** Optional one-to-two sentence TLDR generated by the reasoning model. */
  summary?: string
}

// ── Two-panel workspace (TIN-1640) ──────────────────────────────────────────

/** Which side of the split a panel is. */
export type PanelSide = 'left' | 'right'

/** One open document tab in a panel — just its path. A note is its content; its
 *  links live in a footer, and changes (diff) are a separate destination, so a
 *  document no longer has per-document surface tabs. */
export interface OpenDoc {
  path: string
}

/** Independent state for a single panel: the open document tabs (left→right
 *  strip order) and which one is active. The Search tab is implicit and always
 *  leftmost; `activeTabId === null` means Search is active. Persisted per side
 *  in localStorage. */
export interface PanelState {
  tabs: OpenDoc[]
  activeTabId: string | null
}

/** Legacy per-panel state shape (TIN-1640), kept only for one-time migration of
 *  the persisted layout into the new {@link PanelState}. */
export interface LegacyPanelState {
  activePath: string | null
  /** Legacy surface ('content' | 'links' | 'diff'); ignored on migration now
   *  that documents have no surface tabs. */
  activeTab?: string
}

/** Cached, parsed contents of a loaded file, shared across both panels so a
 *  file open in both stays in sync and edits route by path. */
export interface LoadedFile {
  content: string
  raw: string
  meta: MemorySearchResult | null
  loading: boolean
}

// A single search result from the FTS5 API
export interface MemorySearchResult {
  path: string
  name: string
  type: string
  projects: string[]
  created: string
  updated: string
  tags: string[]
  status: string
  excerpt: string
}
