//! frontmatter.rs
//!
//! Rule-based frontmatter manager for TIN-1638. Three jobs, all local and
//! instant (no LLM):
//!
//!   1. `generate` — analyse a markdown body and suggest a full frontmatter set
//!      (name, type, projects, tags, created, status). Drives smart generation
//!      on create (Surface 1) and the import flow (Surface 2).
//!   2. `audit` — scan every memory file and report its frontmatter health
//!      (complete / partial / missing). Drives the audit view (Surface 3).
//!   3. `import_markdown` — write an existing markdown body into the memory root
//!      with a generated/edited frontmatter block prepended, body preserved.
//!
//! The classifier is pure and table-driven so each rule is unit-testable in
//! isolation (it is an evaluator + resolver, not CRUD — see the tests).

use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};

use chrono::Local;
use gray_matter::engine::YAML;
use gray_matter::{Matter, Pod};
use serde::{Deserialize, Serialize};
use tauri::State;

use crate::search::Db;

// ── Types ────────────────────────────────────────────────────────────────────

/// A suggested frontmatter set, all fields user-editable before save.
#[derive(Serialize, Deserialize, Clone, Default, PartialEq, Debug)]
#[serde(rename_all = "camelCase")]
pub struct Suggestion {
    /// Slugified identifier (the frontmatter `name` and the filename stem).
    pub name: String,
    /// Human-readable title (first heading / sentence), shown in the preview.
    pub title: String,
    #[serde(rename = "type")]
    pub type_: String,
    pub projects: Vec<String>,
    pub tags: Vec<String>,
    pub created: String,
    pub status: String,
    /// Optional one-to-two sentence TLDR generated by the reasoning model.
    /// `None` when not yet generated (rule-based path leaves this unset).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub summary: Option<String>,
}

/// One row of the frontmatter audit.
#[derive(Serialize, Clone, Default, PartialEq, Debug)]
#[serde(rename_all = "camelCase")]
pub struct AuditEntry {
    pub path: String,
    /// `"complete"` | `"partial"` | `"missing"`.
    pub status: String,
    #[serde(rename = "type")]
    pub type_: String,
    pub projects: Vec<String>,
    pub created: String,
    /// The file's frontmatter `status` field (not the audit status above).
    pub doc_status: String,
    /// Which required fields are absent (`type` / `projects` / `created`).
    pub missing: Vec<String>,
}

// ── Title extraction ──────────────────────────────────────────────────────────

/// The document title: the first `#` heading, else the first sentence, else "".
/// Frontmatter (a leading `---` block) is skipped so we read the prose.
pub fn extract_title(body: &str) -> String {
    let body = strip_frontmatter(body);
    // First ATX heading.
    for line in body.lines() {
        let t = line.trim();
        if let Some(rest) = t.strip_prefix("# ") {
            let h = rest.trim();
            if !h.is_empty() {
                return h.to_string();
            }
        }
    }
    // First non-empty sentence (up to a sentence terminator).
    for line in body.lines() {
        let t = line.trim();
        if t.is_empty() || t.starts_with('#') || t.starts_with("---") {
            continue;
        }
        let end = t
            .find(['.', '!', '?'])
            .map(|i| i + 1)
            .unwrap_or(t.len());
        let sentence = t[..end].trim_end_matches(['.', '!', '?']).trim();
        return sentence.chars().take(80).collect();
    }
    String::new()
}

/// Strip a leading YAML frontmatter block, returning the body after it.
fn strip_frontmatter(raw: &str) -> &str {
    let trimmed = raw.trim_start();
    if !trimmed.starts_with("---") {
        return raw;
    }
    // Find the closing fence after the opening one.
    if let Some(rest) = trimmed.strip_prefix("---") {
        if let Some(end) = rest.find("\n---") {
            let after = &rest[end + 4..];
            return after.trim_start_matches(['\r', '\n']);
        }
    }
    raw
}

// ── Slugify ───────────────────────────────────────────────────────────────────

/// Lowercase, hyphenate, strip non-alphanumerics; collapse runs and trim. Caps
/// at ~60 chars on a word boundary. Mirrors the frontend `slugify`.
pub fn slugify(title: &str) -> String {
    let mut out = String::new();
    let mut prev_dash = false;
    for c in title.chars() {
        if c.is_ascii_alphanumeric() {
            out.extend(c.to_lowercase());
            prev_dash = false;
        } else if !prev_dash && !out.is_empty() {
            out.push('-');
            prev_dash = true;
        }
    }
    let slug = out.trim_matches('-').to_string();
    if slug.len() <= 60 {
        return slug;
    }
    // Trim to the last hyphen within 60 chars so we don't cut a word.
    let cut = slug[..60].rfind('-').unwrap_or(60);
    slug[..cut].trim_matches('-').to_string()
}

// ── Type inference ─────────────────────────────────────────────────────────────

/// Classify the document type from content patterns. Ordered: the first rule
/// that matches wins (feedback is the most specific signal, project the default).
pub fn infer_type(body: &str) -> String {
    let lower = body.to_lowercase();

    // Feedback memories carry the canonical "Why:" + "How to apply:" scaffold.
    if lower.contains("why:") && lower.contains("how to apply:") {
        return "feedback".to_string();
    }
    // A pointer to an external resource, when that's the dominant content.
    if is_reference(body, &lower) {
        return "reference".to_string();
    }
    // About Rob personally (preferences / identity), without a product/ticket.
    if is_user(&lower) {
        return "user".to_string();
    }
    // Default: project work (decisions, tickets, product context).
    "project".to_string()
}

/// A reference is short and dominated by an external link.
fn is_reference(body: &str, lower: &str) -> bool {
    let has_url = lower.contains("http://") || lower.contains("https://");
    if !has_url {
        return false;
    }
    // "dominant" = short doc, or an explicit pointer phrase.
    let words = body.split_whitespace().count();
    lower.contains("see http")
        || lower.contains("link:")
        || lower.contains("url:")
        || words < 40
}

/// A user memory is about Rob's preferences/identity and names no product/ticket.
fn is_user(lower: &str) -> bool {
    if lower.contains("tin-") {
        return false;
    }
    let mentions_rob = lower.contains("rob");
    let preference = lower.contains("prefer")
        || lower.contains("likes")
        || lower.contains("dislikes")
        || lower.contains("wants")
        || lower.contains("always")
        || lower.contains("never");
    mentions_rob && preference
}

// ── Project inference ──────────────────────────────────────────────────────────

/// Detect which known projects the body mentions (case-insensitive, whole word),
/// preserving the order of `known`. Used so a note lands in the right folder.
pub fn infer_projects(body: &str, known: &[String]) -> Vec<String> {
    let lower = body.to_lowercase();
    let mut hits = Vec::new();
    for p in known {
        let needle = p.to_lowercase();
        if needle.is_empty() {
            continue;
        }
        if contains_word(&lower, &needle) {
            hits.push(p.clone());
        }
    }
    hits
}

/// Whole-word containment: `needle` appears in `haystack` bounded by non-alnum.
fn contains_word(haystack: &str, needle: &str) -> bool {
    let bytes = haystack.as_bytes();
    let mut from = 0;
    while let Some(rel) = haystack[from..].find(needle) {
        let start = from + rel;
        let end = start + needle.len();
        let before_ok = start == 0 || !is_word_byte(bytes[start - 1]);
        let after_ok = end >= bytes.len() || !is_word_byte(bytes[end]);
        if before_ok && after_ok {
            return true;
        }
        from = start + 1;
    }
    false
}

fn is_word_byte(b: u8) -> bool {
    b.is_ascii_alphanumeric()
}

// ── Tag extraction ─────────────────────────────────────────────────────────────

/// Top keywords by frequency over a stopword list. Returns up to 5, longest-ties
/// broken by first appearance. Words shorter than 3 chars and pure numbers drop.
pub fn extract_tags(body: &str) -> Vec<String> {
    let body = strip_frontmatter(body);
    let mut counts: HashMap<String, usize> = HashMap::new();
    let mut order: Vec<String> = Vec::new();

    for raw in body.split(|c: char| !c.is_alphanumeric()) {
        if raw.len() < 3 {
            continue;
        }
        let w = raw.to_lowercase();
        if w.chars().all(|c| c.is_ascii_digit()) || STOPWORDS.contains(&w.as_str()) {
            continue;
        }
        if !counts.contains_key(&w) {
            order.push(w.clone());
        }
        *counts.entry(w).or_insert(0) += 1;
    }

    // Sort by (count desc, first-seen asc) for stable, sensible output.
    let mut idx: HashMap<&str, usize> = HashMap::new();
    for (i, w) in order.iter().enumerate() {
        idx.insert(w.as_str(), i);
    }
    let mut words: Vec<String> = counts.keys().cloned().collect();
    words.sort_by(|a, b| {
        counts[b]
            .cmp(&counts[a])
            .then_with(|| idx[a.as_str()].cmp(&idx[b.as_str()]))
    });
    words.into_iter().take(5).collect()
}

/// A compact stopword list — enough to keep tags meaningful without a corpus.
const STOPWORDS: &[&str] = &[
    "the", "and", "for", "are", "but", "not", "you", "all", "any", "can", "had", "her", "was",
    "one", "our", "out", "day", "get", "has", "him", "his", "how", "man", "new", "now", "old",
    "see", "two", "way", "who", "boy", "did", "its", "let", "put", "say", "she", "too", "use",
    "this", "that", "with", "from", "they", "have", "what", "when", "your", "will", "would",
    "there", "their", "which", "about", "into", "than", "then", "them", "these", "some", "more",
    "could", "should", "because", "been", "were", "also", "just", "like", "over", "such", "only",
    "very", "much", "many", "most", "each", "other", "thing", "things", "where", "while", "here",
];

// ── Generate ───────────────────────────────────────────────────────────────────

/// Produce a full suggestion from a markdown body. `today` is injected for
/// determinism; `known_projects` is the set to match against.
/// Rule-based only — `summary` is always `None` (no LLM called here).
pub fn generate(body: &str, today: &str, known_projects: &[String]) -> Suggestion {
    let title = extract_title(body);
    Suggestion {
        name: slugify(&title),
        title,
        type_: infer_type(body),
        projects: infer_projects(body, known_projects),
        tags: extract_tags(body),
        created: today.to_string(),
        status: "active".to_string(),
        summary: None,
    }
}

// ── Audit ──────────────────────────────────────────────────────────────────────

/// Classify a single file's frontmatter health from its raw content.
pub fn audit_one(path: &str, raw: &str) -> AuditEntry {
    let trimmed = raw.trim_start();
    if !trimmed.starts_with("---") {
        return AuditEntry {
            path: path.to_string(),
            status: "missing".to_string(),
            missing: vec!["type".into(), "projects".into(), "created".into()],
            ..Default::default()
        };
    }

    let matter = Matter::<YAML>::new();
    let parsed = matter.parse(raw).ok();
    let map = parsed
        .as_ref()
        .and_then(|p| p.data.as_ref())
        .and_then(|d: &Pod| d.as_hashmap().ok())
        .unwrap_or_default();

    let type_ = pod_str(&map, "type");
    let projects = pod_str_list(&map, "projects");
    let created = pod_str(&map, "created");
    let doc_status = pod_str(&map, "status");

    let mut missing = Vec::new();
    if type_.is_empty() {
        missing.push("type".to_string());
    }
    if projects.is_empty() {
        missing.push("projects".to_string());
    }
    if created.is_empty() {
        missing.push("created".to_string());
    }

    let status = if missing.is_empty() { "complete" } else { "partial" };
    AuditEntry {
        path: path.to_string(),
        status: status.to_string(),
        type_,
        projects,
        created,
        doc_status,
        missing,
    }
}

fn pod_str(map: &HashMap<String, Pod>, key: &str) -> String {
    map.get(key).and_then(|p| p.as_string().ok()).unwrap_or_default()
}

fn pod_str_list(map: &HashMap<String, Pod>, key: &str) -> Vec<String> {
    match map.get(key) {
        Some(p) => {
            if let Ok(items) = p.as_vec() {
                items.iter().filter_map(|x| x.as_string().ok()).filter(|s| !s.is_empty()).collect()
            } else if let Ok(s) = p.as_string() {
                if s.is_empty() { Vec::new() } else { vec![s] }
            } else {
                Vec::new()
            }
        }
        None => Vec::new(),
    }
}

/// Recursively collect `.md` files (skipping hidden + `MEMORY.md`).
fn collect_md(dir: &Path, out: &mut Vec<PathBuf>) {
    let entries = match fs::read_dir(dir) {
        Ok(e) => e,
        Err(_) => return,
    };
    for entry in entries.flatten() {
        let name = entry.file_name();
        let name = name.to_string_lossy();
        if name.starts_with('.') {
            continue;
        }
        let full = entry.path();
        if full.is_dir() {
            collect_md(&full, out);
        } else if name.ends_with(".md") && name != "MEMORY.md" {
            out.push(full);
        }
    }
}

// ── Frontmatter rendering / import ─────────────────────────────────────────────

/// Render a YAML frontmatter block from a suggestion (no body).
fn render_frontmatter(s: &Suggestion) -> String {
    let mut out = String::from("---\n");
    out.push_str(&format!("name: {}\n", s.name));
    out.push_str(&format!("type: {}\n", s.type_));
    out.push_str(&format!("projects: {}\n", yaml_list(&s.projects)));
    out.push_str(&format!("created: {}\n", s.created));
    out.push_str(&format!("updated: {}\n", s.created));
    out.push_str(&format!("tags: {}\n", yaml_list(&s.tags)));
    let status = if s.status.is_empty() { "active" } else { &s.status };
    out.push_str(&format!("status: {status}\n"));
    if let Some(summary) = &s.summary {
        out.push_str(&format!("summary: {}\n", yaml_quote(summary)));
    }
    out.push_str("---\n");
    out
}

/// Quote a string for YAML scalar if it contains characters that require it
/// (colons followed by space, leading/trailing whitespace, quote chars, etc.).
/// Uses double-quoted style with minimal escaping.
fn yaml_quote(s: &str) -> String {
    // Needs quoting if: contains colon+space, starts with special YAML chars,
    // contains a double-quote or backslash, or contains newlines.
    let needs_quote = s.contains(": ")
        || s.contains('"')
        || s.contains('\\')
        || s.contains('\n')
        || s.starts_with([':', '#', '&', '*', '!', '|', '>', '\'', '{', '[', '-']);
    if !needs_quote {
        return s.to_string();
    }
    // Escape backslashes and double-quotes, then wrap in double-quotes.
    let escaped = s.replace('\\', "\\\\").replace('"', "\\\"");
    format!("\"{escaped}\"")
}

/// YAML for a string list: `[]`, a scalar, or a block sequence.
fn yaml_list(values: &[String]) -> String {
    match values.len() {
        0 => "[]".to_string(),
        1 => values[0].clone(),
        _ => {
            let mut out = String::from("\n");
            for v in values {
                out.push_str(&format!("  - {v}\n"));
            }
            out.pop();
            out
        }
    }
}

/// Prepend `frontmatter` to `body`, replacing any existing leading block. The
/// body content after the closing `---` is preserved exactly.
pub fn apply_frontmatter(body: &str, suggestion: &Suggestion) -> String {
    let content = strip_frontmatter(body).trim_start();
    format!("{}\n{}", render_frontmatter(suggestion), content)
}

// ── Commands ───────────────────────────────────────────────────────────────────

/// Known project names from the index, used to seed project inference. Falls
/// back to the default domains if the query fails / the index is empty.
fn known_projects(db: &State<'_, Db>) -> Vec<String> {
    const DEFAULTS: &[&str] = &["attic", "understory", "rearview", "website", "studio", "shared"];
    let from_db = db.0.lock().ok().and_then(|conn| {
        conn.prepare("SELECT DISTINCT projects FROM memory_files WHERE projects != ''")
            .ok()
            .and_then(|mut stmt| {
                let rows = stmt
                    .query_map([], |r| r.get::<_, String>(0))
                    .ok()?
                    .filter_map(Result::ok)
                    .collect::<Vec<_>>();
                Some(rows)
            })
    });

    let mut set: Vec<String> = DEFAULTS.iter().map(|s| s.to_string()).collect();
    if let Some(rows) = from_db {
        for joined in rows {
            for p in joined.split(',').filter(|s| !s.is_empty()) {
                if !set.iter().any(|x| x == p) {
                    set.push(p.to_string());
                }
            }
        }
    }
    set
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SuggestInput {
    pub content: String,
}

#[tauri::command]
pub fn suggest_frontmatter(payload: SuggestInput, db: State<'_, Db>) -> Result<Suggestion, String> {
    let today = Local::now().format("%Y-%m-%d").to_string();
    Ok(generate(&payload.content, &today, &known_projects(&db)))
}

#[tauri::command]
pub fn audit_frontmatter(
    db: State<'_, Db>,
    memory: State<'_, crate::settings::MemoryRoot>,
) -> Result<Vec<AuditEntry>, String> {
    let _ = &db; // kept for signature symmetry / future per-file DB lookups
    let root = memory
        .0
        .lock()
        .map(|g| g.clone())
        .unwrap_or_else(|_| crate::settings::default_memory_root());

    let mut files = Vec::new();
    collect_md(&root, &mut files);
    let mut entries = Vec::new();
    for path in files {
        let raw = fs::read_to_string(&path).unwrap_or_default();
        let mut entry = audit_one(&path.to_string_lossy(), &raw);
        // Attach the file's last-modified date as the created fallback display.
        if entry.created.is_empty() {
            if let Ok(meta) = fs::metadata(&path) {
                if let Ok(modified) = meta.modified() {
                    let dt: chrono::DateTime<Local> = modified.into();
                    entry.created = dt.format("%Y-%m-%d").to_string();
                    // Don't clear `missing` — created is still absent in the file.
                }
            }
        }
        entries.push(entry);
    }
    // Unhealthy first (missing, then partial, then complete), then by path.
    let rank = |s: &str| match s {
        "missing" => 0,
        "partial" => 1,
        _ => 2,
    };
    entries.sort_by(|a, b| rank(&a.status).cmp(&rank(&b.status)).then_with(|| a.path.cmp(&b.path)));
    Ok(entries)
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ImportInput {
    /// The markdown body to import (may or may not already have frontmatter).
    pub content: String,
    /// The frontmatter to write (user-reviewed).
    pub frontmatter: Suggestion,
}

#[tauri::command]
pub fn import_markdown(
    payload: ImportInput,
    db: State<'_, Db>,
    memory: State<'_, crate::settings::MemoryRoot>,
) -> Result<String, String> {
    let s = &payload.frontmatter;
    if s.name.trim().is_empty() || s.type_.trim().is_empty() || s.projects.is_empty() {
        return Err("name, type, and at least one project are required".to_string());
    }
    let root = memory.0.lock().map_err(|e| e.to_string())?.clone();
    let dir = root.join(&s.projects[0]);
    fs::create_dir_all(&dir).map_err(|e| e.to_string())?;
    let path = dir.join(format!("{}.md", s.name));
    if path.exists() {
        return Err("File already exists".to_string());
    }
    fs::write(&path, apply_frontmatter(&payload.content, s)).map_err(|e| e.to_string())?;

    // Rebuild the index so the imported file is searchable immediately.
    let conn = db.0.lock().map_err(|e| e.to_string())?;
    crate::search::build_index(&root, &conn).map_err(|e| e.to_string())?;
    Ok(path.to_string_lossy().to_string())
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UpdateInput {
    /// Absolute path of an existing memory file to repair.
    pub path: String,
    /// The reviewed frontmatter to write in place (body preserved).
    pub frontmatter: Suggestion,
}

/// Rewrite an existing file's frontmatter in place (the audit "fix" path). The
/// body after the block is preserved exactly; the index is rebuilt after.
#[tauri::command]
pub fn update_frontmatter(
    payload: UpdateInput,
    db: State<'_, Db>,
    memory: State<'_, crate::settings::MemoryRoot>,
) -> Result<(), String> {
    let s = &payload.frontmatter;
    if s.type_.trim().is_empty() || s.projects.is_empty() {
        return Err("type and at least one project are required".to_string());
    }
    let raw = fs::read_to_string(&payload.path).map_err(|e| e.to_string())?;
    fs::write(&payload.path, apply_frontmatter(&raw, s)).map_err(|e| e.to_string())?;

    let root = memory.0.lock().map_err(|e| e.to_string())?.clone();
    let conn = db.0.lock().map_err(|e| e.to_string())?;
    crate::search::build_index(&root, &conn).map_err(|e| e.to_string())?;
    Ok(())
}

// ── Summarize command ──────────────────────────────────────────────────────────

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SummarizeNoteInput {
    pub content: String,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct SummarizeNoteOutput {
    pub summary: String,
    pub degraded: bool,
}

const SUMMARIZE_SYSTEM: &str = "\
Write a one or two sentence TLDR of this note. Plain text only — no preamble, \
no markdown, no filler phrases like 'This note is about'. Start directly with \
the substance.";

/// Generate a short TLDR summary of a note using the local reasoning model.
/// If no reasoning model is reachable, returns `{ summary: \"\", degraded: true }`
/// so the caller can degrade gracefully — this command never returns an error.
#[tauri::command]
pub async fn summarize_note(payload: SummarizeNoteInput) -> SummarizeNoteOutput {
    if !crate::reason::reachable().await {
        return SummarizeNoteOutput { summary: String::new(), degraded: true };
    }
    match crate::reason::complete(SUMMARIZE_SYSTEM, &payload.content).await {
        Ok(text) => SummarizeNoteOutput { summary: text.trim().to_string(), degraded: false },
        Err(_) => SummarizeNoteOutput { summary: String::new(), degraded: true },
    }
}

// ── Confidence suggestions (TIN-1758) ───────────────────────────────────────────
//
// Per-field confidence by provenance, folded to a per-file band by the MINIMUM
// across missing fields (a file is only as settled as its weakest field). The
// scoring composition is a pure function (`compose_field`) so each rung of the
// confidence ladder is unit-testable without IO or a model.

/// Per-field confidence rungs, by provenance (Jonny's blessed ladder).
mod conf {
    /// Folder under the memory root pins the field (e.g. `attic/x.md` → attic).
    pub const PATH_DERIVED: f32 = 0.97;
    /// Rule-based and the model independently agree.
    pub const AGREE: f32 = 0.95;
    /// `created` taken from the file's modified time.
    pub const FILE_DATE: f32 = 0.90;
    /// Rule-based only, an unambiguous single match.
    pub const RULE_ONLY: f32 = 0.80;
    /// LLM-only inference is capped here (the model's own score, clamped down).
    pub const LLM_CAP: f32 = 0.75;
    /// Two methods disagree, or nothing matched at all.
    pub const NONE: f32 = 0.30;
}

/// Band thresholds (inclusive lower bounds). Mirrored by the frontend `bandOf`
/// in `lib/frontmatter.ts`; the overall score crosses the IPC boundary and the
/// UI bands it, so these are exercised by `band()` in tests on the Rust side.
#[allow(dead_code)]
const BAND_SETTLED: f32 = 0.85;
#[allow(dead_code)]
const BAND_LIKELY: f32 = 0.55;

/// One field's resolved value plus how sure we are and where it came from.
#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
#[serde(rename_all = "camelCase")]
pub struct FieldConfidence {
    pub value: String,
    pub confidence: f32,
    /// Provenance tag: `"path"` | `"agree"` | `"file-date"` | `"rules"` |
    /// `"model"` | `"none"`. Drives the micro-label in the UI.
    pub source: String,
}

/// A full confidence-scored suggestion for one file: the suggestion itself, the
/// per-field confidences for the fields that were missing, the per-file overall
/// (the minimum across those fields), and whether the model was unavailable.
#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
#[serde(rename_all = "camelCase")]
pub struct ConfidenceResult {
    /// Absolute path of the file this suggestion is for.
    pub path: String,
    pub suggestion: Suggestion,
    /// Confidence per missing field, keyed by `"type"` | `"projects"` | `"created"`.
    pub fields: HashMap<String, FieldConfidence>,
    /// Per-file band score = the MINIMUM across `fields` (1.0 when none missing).
    pub overall: f32,
    /// True when no reasoning model was reachable (rules + path only).
    pub degraded: bool,
}

/// Map an overall score to its band label. Settled ≥0.85, Likely 0.55–0.84,
/// else Unsure. Pure so the frontend and tests can agree on the cut points.
/// (The UI bands the `overall` itself via `bandOf`; this is the Rust mirror,
/// asserted in tests to keep the two cut-point sets honest.)
#[allow(dead_code)]
pub fn band(score: f32) -> &'static str {
    if score >= BAND_SETTLED {
        "settled"
    } else if score >= BAND_LIKELY {
        "likely"
    } else {
        "unsure"
    }
}

/// Derive a `project` hint from a file's path relative to the memory root. The
/// first path segment under the root that is a known project folder pins the
/// project at `PATH_DERIVED` (e.g. `…/memory/attic/x.md` → attic). Type is never
/// path-derived today (folders are by project, not type).
///
/// Returns `None` when the file is not under a known-project folder (e.g.
/// directly in the root, or under an unknown folder).
pub fn path_project(path: &str, root: &Path, known_projects: &[String]) -> Option<String> {
    let p = Path::new(path);
    let rel = p.strip_prefix(root).ok()?;
    // The first component of the relative path is the folder under the root.
    let first = rel.components().next()?;
    let folder = first.as_os_str().to_string_lossy().to_string();
    if folder.is_empty() {
        return None;
    }
    known_projects
        .iter()
        .find(|kp| kp.eq_ignore_ascii_case(&folder))
        .cloned()
}

/// Compose the confidence for a single field from its three possible sources:
/// a path-derived value (highest authority), the rule-based value, and an
/// optional model value with the model's own score. Pure — the heart of the
/// ladder, unit-tested rung by rung.
///
/// Precedence:
///   1. path-derived present                       → PATH_DERIVED (0.97)
///   2. rule + model present and equal             → AGREE (0.95)
///   3. rule + model present and DIFFERENT          → NONE (0.30), keep rule value
///   4. rule only (non-empty)                      → RULE_ONLY (0.80)
///   5. model only (non-empty)                     → min(model_score, LLM_CAP)
///   6. nothing matched                            → NONE (0.30), empty value
fn compose_field(
    path_derived: Option<&str>,
    rule_value: &str,
    model: Option<(&str, f32)>,
) -> FieldConfidence {
    if let Some(pv) = path_derived.filter(|s| !s.is_empty()) {
        return FieldConfidence { value: pv.to_string(), confidence: conf::PATH_DERIVED, source: "path".into() };
    }
    let rule = rule_value.trim();
    let model = model.filter(|(v, _)| !v.trim().is_empty());

    match (!rule.is_empty(), model) {
        (true, Some((mv, _))) => {
            if rule.eq_ignore_ascii_case(mv.trim()) {
                FieldConfidence { value: rule.to_string(), confidence: conf::AGREE, source: "agree".into() }
            } else {
                // Two methods disagree — keep the rule value but mark it unsure.
                FieldConfidence { value: rule.to_string(), confidence: conf::NONE, source: "none".into() }
            }
        }
        (true, None) => {
            FieldConfidence { value: rule.to_string(), confidence: conf::RULE_ONLY, source: "rules".into() }
        }
        (false, Some((mv, score))) => {
            let capped = score.min(conf::LLM_CAP).max(0.0);
            FieldConfidence { value: mv.trim().to_string(), confidence: capped, source: "model".into() }
        }
        (false, None) => {
            FieldConfidence { value: String::new(), confidence: conf::NONE, source: "none".into() }
        }
    }
}

/// The system prompt for the model's frontmatter inference. Asks for a strict,
/// machine-parseable line per ambiguous field plus a 0..1 confidence. Kept terse
/// so a small local model stays on-format.
const SUGGEST_SYSTEM: &str = "\
You classify a note's frontmatter. Reply with ONLY these lines, nothing else, \
no preamble:\n\
TYPE: <one of feedback|reference|user|project> <confidence 0..1>\n\
PROJECT: <one short project slug, or NONE> <confidence 0..1>\n\
Confidence is your own certainty as a decimal. No markdown, no explanation.";

/// One field the model returned: a value and the model's self-reported score.
#[derive(Default, Clone)]
struct ModelField {
    value: String,
    score: f32,
}

/// Parse the strict two-line model reply into `(type, project)` model fields.
/// Tolerant of casing and missing lines — an unparseable line yields an empty
/// field (which `compose_field` treats as "model absent").
fn parse_model_reply(reply: &str) -> (ModelField, ModelField) {
    let mut type_f = ModelField::default();
    let mut proj_f = ModelField::default();
    for line in reply.lines() {
        let line = line.trim();
        let (key, rest) = match line.split_once(':') {
            Some((k, r)) => (k.trim().to_ascii_uppercase(), r.trim()),
            None => continue,
        };
        // Last whitespace-separated token is the score; the rest is the value.
        let (value, score) = match rest.rsplit_once(char::is_whitespace) {
            Some((v, s)) => (v.trim(), s.trim().parse::<f32>().unwrap_or(0.0)),
            None => (rest, 0.0),
        };
        let value = if value.eq_ignore_ascii_case("none") { "" } else { value };
        match key.as_str() {
            "TYPE" => type_f = ModelField { value: value.to_string(), score },
            "PROJECT" => proj_f = ModelField { value: value.to_string(), score },
            _ => {}
        }
    }
    (type_f, proj_f)
}

/// Build a confidence result for one file, given its already-computed rule-based
/// suggestion, the path-derived project hint, the file's mtime date, the set of
/// missing fields, and an optional model reply. Pure of IO and async so it is
/// fully unit-testable; the command wrappers do the IO and call this.
#[allow(clippy::too_many_arguments)]
fn build_result(
    path: &str,
    rules: &Suggestion,
    path_proj: Option<&str>,
    file_date: &str,
    missing: &[String],
    model_reply: Option<&str>,
    summary: Option<String>,
    degraded: bool,
) -> ConfidenceResult {
    let (m_type, m_proj) = match model_reply {
        Some(r) => parse_model_reply(r),
        None => (ModelField::default(), ModelField::default()),
    };

    let mut suggestion = rules.clone();
    suggestion.summary = summary;
    let mut fields: HashMap<String, FieldConfidence> = HashMap::new();

    for field in missing {
        match field.as_str() {
            "type" => {
                let model = if m_type.value.is_empty() { None } else { Some((m_type.value.as_str(), m_type.score)) };
                let fc = compose_field(None, &rules.type_, model);
                suggestion.type_ = fc.value.clone();
                fields.insert("type".into(), fc);
            }
            "projects" => {
                // Rule-based projects: a single unambiguous match is RULE_ONLY;
                // zero or many is "no clean rule value" (empty rule input).
                let rule_one = if rules.projects.len() == 1 { rules.projects[0].as_str() } else { "" };
                let model = if m_proj.value.is_empty() { None } else { Some((m_proj.value.as_str(), m_proj.score)) };
                let fc = compose_field(path_proj, rule_one, model);
                suggestion.projects = if fc.value.is_empty() { Vec::new() } else { vec![fc.value.clone()] };
                fields.insert("projects".into(), fc);
            }
            "created" => {
                // `created` comes from the file's mtime when absent in the file.
                let fc = if file_date.is_empty() {
                    FieldConfidence { value: String::new(), confidence: conf::NONE, source: "none".into() }
                } else {
                    FieldConfidence { value: file_date.to_string(), confidence: conf::FILE_DATE, source: "file-date".into() }
                };
                suggestion.created = fc.value.clone();
                fields.insert("created".into(), fc);
            }
            _ => {}
        }
    }

    // Per-file overall = the MINIMUM across the missing fields (min, never blend).
    let overall = fields
        .values()
        .map(|f| f.confidence)
        .fold(f32::INFINITY, f32::min);
    let overall = if overall.is_finite() { overall } else { 1.0 };

    ConfidenceResult { path: path.to_string(), suggestion, fields, overall, degraded }
}

/// Whether a missing-field set needs the model at all. Path/rule resolve type
/// and project for free in the common case; we only pay an LLM call when a field
/// would otherwise be ambiguous (no path hint, and rules gave 0 or >1 matches).
fn needs_model(missing: &[String], rules: &Suggestion, path_proj: Option<&str>) -> bool {
    for field in missing {
        match field.as_str() {
            "type" => {
                // Rules always return a type (project is the default), so type is
                // never *empty* — but the default is a weak guess. We ask the
                // model to confirm only when rules fell back to the default.
                if rules.type_.is_empty() || rules.type_ == "project" {
                    return true;
                }
            }
            "projects" => {
                if path_proj.is_none() && rules.projects.len() != 1 {
                    return true;
                }
            }
            _ => {}
        }
    }
    false
}

// ── Inputs / outputs ─────────────────────────────────────────────────────────

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SuggestWithConfidenceInput {
    pub path: String,
    /// The note body. May be empty — when blank, the file is read from `path`,
    /// so the row-expand path does not need a separate frontend file read.
    #[serde(default)]
    pub content: String,
    /// Known vocab accepted per the blessed payload contract. `known_projects`
    /// seeds project inference; `known_types` / `known_tags` are reserved for a
    /// future model prompt and are part of the IPC shape today.
    #[serde(default)]
    #[allow(dead_code)]
    pub known_types: Vec<String>,
    #[serde(default)]
    pub known_projects: Vec<String>,
    #[serde(default)]
    #[allow(dead_code)]
    pub known_tags: Vec<String>,
}

/// File mtime formatted `YYYY-MM-DD`, or empty if unavailable.
fn file_mtime_date(path: &str) -> String {
    fs::metadata(path)
        .and_then(|m| m.modified())
        .map(|t| {
            let dt: chrono::DateTime<Local> = t.into();
            dt.format("%Y-%m-%d").to_string()
        })
        .unwrap_or_default()
}

/// Core per-file suggestion: compose path-derived + rule-based + (optional) LLM
/// confidences. Shared by the single-file command and the bulk pass. Degrades to
/// rules+path with `degraded: true` when no model is reachable — never errors.
async fn suggest_one(
    path: &str,
    content: &str,
    today: &str,
    root: &Path,
    known_projects: &[String],
    model_up: bool,
) -> ConfidenceResult {
    let audit = audit_one(path, content);
    let rules = generate(content, today, known_projects);
    let path_proj = path_project(path, root, known_projects);
    let file_date = file_mtime_date(path);

    // Only call the model when a field is genuinely ambiguous AND a model is up.
    let want_model = model_up && needs_model(&audit.missing, &rules, path_proj.as_deref());
    let model_reply = if want_model {
        crate::reason::complete(SUGGEST_SYSTEM, content).await.ok()
    } else {
        None
    };

    // Summary via the existing local TLDR, best-effort (only if a model is up).
    let summary = if model_up {
        crate::reason::complete(SUMMARIZE_SYSTEM, content)
            .await
            .ok()
            .map(|s| s.trim().to_string())
            .filter(|s| !s.is_empty())
    } else {
        None
    };

    build_result(
        path,
        &rules,
        path_proj.as_deref(),
        &file_date,
        &audit.missing,
        model_reply.as_deref(),
        summary,
        !model_up,
    )
}

/// Confidence-scored suggestion for a single file (the per-row expand path).
/// Never errors: with no model it returns the rules+path result, `degraded:true`.
#[tauri::command]
pub async fn suggest_with_confidence(
    payload: SuggestWithConfidenceInput,
    memory: State<'_, crate::settings::MemoryRoot>,
) -> Result<ConfidenceResult, String> {
    let root = memory
        .0
        .lock()
        .map(|g| g.clone())
        .unwrap_or_else(|_| crate::settings::default_memory_root());
    let mut known = payload.known_projects.clone();
    if known.is_empty() {
        known = DEFAULT_PROJECTS.iter().map(|s| s.to_string()).collect();
    }
    let today = Local::now().format("%Y-%m-%d").to_string();
    let model_up = crate::reason::reachable().await;
    // Empty content → read the file from disk so the caller need not.
    let content = if payload.content.is_empty() {
        fs::read_to_string(&payload.path).unwrap_or_default()
    } else {
        payload.content.clone()
    };
    Ok(suggest_one(&payload.path, &content, &today, &root, &known, model_up).await)
}

const DEFAULT_PROJECTS: &[&str] =
    &["attic", "understory", "rearview", "website", "studio", "shared"];

/// Background pass: confidence-score every unhealthy file, emitting
/// `audit://progress {done,total}` per file. Mirrors `consistency_audit`
/// structurally. Path/rule-only files cost no LLM call. Degrades calmly with no
/// model (still covers the folder-certain majority).
#[tauri::command]
pub async fn suggest_all(
    app: tauri::AppHandle,
    memory: State<'_, crate::settings::MemoryRoot>,
) -> Result<Vec<ConfidenceResult>, String> {
    use tauri::Emitter;

    let root = memory
        .0
        .lock()
        .map(|g| g.clone())
        .unwrap_or_else(|_| crate::settings::default_memory_root());

    // Gather the unhealthy files (collect_md + audit_one), like the audit view.
    let mut files = Vec::new();
    collect_md(&root, &mut files);
    let mut work: Vec<(String, String)> = Vec::new();
    for path in files {
        let raw = fs::read_to_string(&path).unwrap_or_default();
        let entry = audit_one(&path.to_string_lossy(), &raw);
        if entry.status != "complete" {
            work.push((path.to_string_lossy().to_string(), raw));
        }
    }

    let known: Vec<String> = {
        // Reuse known projects from defaults + any folder names actually present.
        let mut set: Vec<String> = DEFAULT_PROJECTS.iter().map(|s| s.to_string()).collect();
        if let Ok(entries) = fs::read_dir(&root) {
            for e in entries.flatten() {
                if e.path().is_dir() {
                    let name = e.file_name().to_string_lossy().to_string();
                    if !name.starts_with('.') && !set.iter().any(|x| x == &name) {
                        set.push(name);
                    }
                }
            }
        }
        set
    };

    let today = Local::now().format("%Y-%m-%d").to_string();
    let model_up = crate::reason::reachable().await;
    let total = work.len();
    let mut out = Vec::with_capacity(total);

    for (idx, (path, content)) in work.into_iter().enumerate() {
        let res = suggest_one(&path, &content, &today, &root, &known, model_up).await;
        // Stream each suggestion the moment it is ready, so rows light up live
        // instead of the user waiting for the whole pass (TIN-1758 follow-up).
        let _ = app.emit("suggest://result", &res);
        let _ = app.emit("audit://progress", AuditProgress { done: idx + 1, total });
        out.push(res);
    }

    Ok(out)
}

/// Progress payload (mirrors `audit.rs`'s, kept local so the two passes stay
/// independent while sharing the `audit://progress` channel + frontend listener).
#[derive(Serialize, Clone)]
#[serde(rename_all = "camelCase")]
struct AuditProgress {
    done: usize,
    total: usize,
}

// ── Apply (single + bulk) ────────────────────────────────────────────────────

#[derive(Deserialize, Clone)]
#[serde(rename_all = "camelCase")]
pub struct ApplySuggestionInput {
    pub path: String,
    pub suggestion: Suggestion,
    /// The actor id to record (the model name, or `"rules"` when degraded).
    #[serde(default)]
    pub actor_id: String,
}

/// Write one file's suggested frontmatter (body-preserving) and record a
/// memory_audit row. Does NOT rebuild the index here — callers decide when to
/// reindex (single: right after; bulk: once at the end).
fn apply_one(
    conn: &rusqlite::Connection,
    input: &ApplySuggestionInput,
) -> Result<(), String> {
    let raw = fs::read_to_string(&input.path).map_err(|e| e.to_string())?;
    let new_content = apply_frontmatter(&raw, &input.suggestion);
    fs::write(&input.path, &new_content).map_err(|e| e.to_string())?;

    let actor_id = if input.actor_id.trim().is_empty() { "rules" } else { input.actor_id.trim() };
    let record = crate::memory_audit::RecordMemoryChangeInput {
        path: input.path.clone(),
        actor_type: "agent".into(),
        actor_id: actor_id.to_string(),
        continuity_score: None,
        change_summary: "filled type, project, created".into(),
        content_hash: crate::memory_audit::content_hash(&new_content),
    };
    crate::memory_audit::record_change(conn, &record).map_err(|e| e.to_string())?;
    Ok(())
}

/// Apply one file's suggested frontmatter, record the change, and rebuild the
/// index so the row re-resolves with the new state.
#[tauri::command]
pub fn apply_suggestion(
    payload: ApplySuggestionInput,
    db: State<'_, Db>,
    memory: State<'_, crate::settings::MemoryRoot>,
) -> Result<(), String> {
    let conn = db.0.lock().map_err(|e| e.to_string())?;
    apply_one(&conn, &payload)?;
    let root = memory.0.lock().map_err(|e| e.to_string())?.clone();
    crate::search::build_index(&root, &conn).map_err(|e| e.to_string())?;
    Ok(())
}

/// Apply a batch of suggestions: write each file (body-preserving) + record one
/// audit row each, emitting `audit://progress` per write. Rebuilds the index
/// ONCE at the end (not per file). Returns the count successfully applied.
#[tauri::command]
pub fn apply_suggestions_bulk(
    app: tauri::AppHandle,
    payload: Vec<ApplySuggestionInput>,
    db: State<'_, Db>,
    memory: State<'_, crate::settings::MemoryRoot>,
) -> Result<usize, String> {
    use tauri::Emitter;

    let conn = db.0.lock().map_err(|e| e.to_string())?;
    let total = payload.len();
    let mut done = 0usize;
    for (idx, input) in payload.iter().enumerate() {
        match apply_one(&conn, input) {
            Ok(()) => done += 1,
            Err(e) => log::warn!("[suggest] bulk apply {} failed: {e}", input.path),
        }
        let _ = app.emit("audit://progress", AuditProgress { done: idx + 1, total });
    }

    // Rebuild the index ONCE, after all writes.
    let root = memory.0.lock().map_err(|e| e.to_string())?.clone();
    crate::search::build_index(&root, &conn).map_err(|e| e.to_string())?;
    Ok(done)
}

// ── Tests ──────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    fn known() -> Vec<String> {
        ["attic", "understory", "rearview", "website", "studio", "shared"]
            .iter()
            .map(|s| s.to_string())
            .collect()
    }

    // ── extract_title (resolver) ─────────────────────────────────────────────

    #[test]
    fn title_from_first_heading() {
        assert_eq!(extract_title("intro line\n# The Real Title\nmore"), "The Real Title");
    }

    #[test]
    fn title_from_first_sentence_when_no_heading() {
        assert_eq!(extract_title("This is the lead sentence. And another."), "This is the lead sentence");
    }

    #[test]
    fn title_skips_frontmatter() {
        let body = "---\nname: x\n---\n# Heading After Frontmatter\nbody";
        assert_eq!(extract_title(body), "Heading After Frontmatter");
    }

    // ── slugify ──────────────────────────────────────────────────────────────

    #[test]
    fn slugify_basic_and_punctuation() {
        assert_eq!(slugify("The Real Title!"), "the-real-title");
        assert_eq!(slugify("  Spaces & Symbols -- here  "), "spaces-symbols-here");
        assert_eq!(slugify(""), "");
    }

    // ── infer_type (evaluator — each branch fires) ───────────────────────────

    #[test]
    fn type_feedback_on_why_and_how() {
        let body = "Rob prefers tabs.\n\nWhy: consistency.\nHow to apply: use tabs everywhere.";
        assert_eq!(infer_type(body), "feedback");
    }

    #[test]
    fn type_reference_on_short_link_doc() {
        assert_eq!(infer_type("See https://example.com/spec for details."), "reference");
    }

    #[test]
    fn type_user_on_personal_preference() {
        assert_eq!(infer_type("Rob prefers dark mode and always uses vim."), "user");
    }

    #[test]
    fn type_project_is_the_default() {
        let body = "The TIN-1638 frontmatter manager will ship in the studio app this sprint.";
        assert_eq!(infer_type(body), "project");
    }

    #[test]
    fn type_user_not_fired_when_ticket_present() {
        // Mentions Rob + preference, but also a ticket → project, not user.
        let body = "Rob prefers we close TIN-1000 first.";
        assert_eq!(infer_type(body), "project");
    }

    // ── infer_projects (resolver — fires + doesn't over-fire) ────────────────

    #[test]
    fn projects_detected_whole_word_only() {
        let body = "Work on the studio app touches the shared design tokens.";
        assert_eq!(infer_projects(body, &known()), vec!["studio".to_string(), "shared".to_string()]);
    }

    #[test]
    fn projects_no_substring_false_positive() {
        // "understory" must NOT match inside "misunderstory" or "story".
        assert!(infer_projects("a short story about nothing", &known()).is_empty());
    }

    // ── extract_tags (combiner) ──────────────────────────────────────────────

    #[test]
    fn tags_rank_by_frequency_drop_stopwords() {
        let body = "Embeddings embeddings embeddings power search search. The the the and and.";
        let tags = extract_tags(body);
        assert_eq!(tags.first().map(|s| s.as_str()), Some("embeddings"), "most frequent content word first");
        assert!(!tags.iter().any(|t| t == "the" || t == "and"), "stopwords excluded");
        assert!(tags.len() <= 5);
    }

    // ── generate (integration of the rules) ──────────────────────────────────

    #[test]
    fn generate_full_suggestion() {
        let body = "# Hybrid Search Notes\n\nThe studio search blends embeddings and ranking. Why: recall. How to apply: enable the key.";
        let s = generate(body, "2026-06-22", &known());
        assert_eq!(s.title, "Hybrid Search Notes");
        assert_eq!(s.name, "hybrid-search-notes");
        assert_eq!(s.type_, "feedback"); // has Why: + How to apply:
        assert_eq!(s.projects, vec!["studio".to_string()]);
        assert_eq!(s.created, "2026-06-22");
        assert_eq!(s.status, "active");
        assert!(!s.tags.is_empty());
    }

    // ── audit_one (state projector — all three states) ───────────────────────

    #[test]
    fn audit_missing_when_no_frontmatter() {
        let e = audit_one("/m/a.md", "Just a body, no frontmatter.");
        assert_eq!(e.status, "missing");
        assert_eq!(e.missing, vec!["type", "projects", "created"]);
    }

    #[test]
    fn audit_partial_when_fields_absent() {
        let raw = "---\nname: a\ntype: feedback\n---\nbody";
        let e = audit_one("/m/a.md", raw);
        assert_eq!(e.status, "partial");
        assert_eq!(e.type_, "feedback");
        assert!(e.missing.contains(&"projects".to_string()));
        assert!(e.missing.contains(&"created".to_string()));
        assert!(!e.missing.contains(&"type".to_string()));
    }

    #[test]
    fn audit_complete_when_all_required_present() {
        let raw = "---\nname: a\ntype: feedback\nprojects: studio\ncreated: 2026-06-22\nstatus: active\n---\nbody";
        let e = audit_one("/m/a.md", raw);
        assert_eq!(e.status, "complete");
        assert!(e.missing.is_empty());
        assert_eq!(e.projects, vec!["studio".to_string()]);
    }

    // ── apply_frontmatter (cascade — body preserved) ─────────────────────────

    #[test]
    fn apply_prepends_and_preserves_body() {
        let s = Suggestion {
            name: "note".into(),
            title: "Note".into(),
            type_: "project".into(),
            projects: vec!["studio".into()],
            tags: vec!["a".into(), "b".into()],
            created: "2026-06-22".into(),
            status: "active".into(),
            summary: None,
        };
        let out = apply_frontmatter("# Note\n\nThe body stays.", &s);
        assert!(out.starts_with("---\nname: note\n"));
        assert!(out.contains("type: project"));
        assert!(out.trim_end().ends_with("The body stays."), "body content preserved");
    }

    #[test]
    fn apply_replaces_existing_frontmatter() {
        let s = Suggestion {
            name: "note".into(),
            title: "Note".into(),
            type_: "feedback".into(),
            projects: vec!["studio".into()],
            tags: vec![],
            created: "2026-06-22".into(),
            status: "active".into(),
            summary: None,
        };
        let existing = "---\nname: old\ntype: project\n---\nThe real body.";
        let out = apply_frontmatter(existing, &s);
        assert_eq!(out.matches("---").count(), 2, "exactly one frontmatter block");
        assert!(out.contains("type: feedback"), "new frontmatter wins");
        assert!(out.contains("The real body."));
        assert!(!out.contains("name: old"));
    }

    // ── summary / render_frontmatter ──────────────────────────────────────────

    fn base_suggestion() -> Suggestion {
        Suggestion {
            name: "test-note".into(),
            title: "Test Note".into(),
            type_: "project".into(),
            projects: vec!["studio".into()],
            tags: vec!["rust".into()],
            created: "2026-06-24".into(),
            status: "active".into(),
            summary: None,
        }
    }

    #[test]
    fn render_includes_summary_when_set() {
        let mut s = base_suggestion();
        s.summary = Some("This is a brief TLDR of the note.".into());
        let out = render_frontmatter(&s);
        assert!(out.contains("summary: This is a brief TLDR of the note."), "summary line present: {out}");
    }

    #[test]
    fn render_omits_summary_when_none() {
        let s = base_suggestion();
        let out = render_frontmatter(&s);
        assert!(!out.contains("summary:"), "summary absent when None: {out}");
    }

    #[test]
    fn render_summary_yaml_safe_with_colon() {
        let mut s = base_suggestion();
        s.summary = Some("Key insight: use async for IO-bound work.".into());
        let out = render_frontmatter(&s);
        // Must be quoted because of ": "
        assert!(out.contains("summary: \"Key insight: use async for IO-bound work.\""), "colon triggers quoting: {out}");
    }

    #[test]
    fn render_summary_yaml_safe_with_double_quote() {
        let mut s = base_suggestion();
        s.summary = Some(r#"Rob said "ship it" last sprint."#.into());
        let out = render_frontmatter(&s);
        // Double-quotes must be escaped inside the YAML double-quoted scalar.
        assert!(out.contains(r#"summary: "Rob said \"ship it\" last sprint.""#), "quotes escaped: {out}");
    }

    #[test]
    fn apply_frontmatter_round_trips_summary() {
        let mut s = base_suggestion();
        s.summary = Some("Decisions made in TIN-1727 sprint.".into());
        let body = "# Test Note\n\nContent here.";
        let out = apply_frontmatter(body, &s);
        assert!(out.contains("summary: Decisions made in TIN-1727 sprint."), "summary survives round-trip: {out}");
        assert!(out.contains("Content here."), "body preserved");
    }

    #[test]
    fn suggest_frontmatter_leaves_summary_none() {
        // Verifies that the rule-based path never populates summary.
        let body = "# Planning Note\n\nThe studio search blends embeddings. Why: recall. How to apply: enable.";
        let s = generate(body, "2026-06-24", &known());
        assert_eq!(s.summary, None, "rule-based generate must leave summary as None");
    }

    // ── summarize_note degraded path ──────────────────────────────────────────

    /// Verify the degraded output type shape without needing a live model.
    /// The async command itself is exercised by the `summarize_note` fn; we
    /// test `SummarizeNoteOutput` fields compile and serialize correctly.
    #[test]
    fn summarize_note_output_degraded_fields() {
        let out = SummarizeNoteOutput { summary: String::new(), degraded: true };
        assert!(out.summary.is_empty());
        assert!(out.degraded);
    }

    #[test]
    fn summarize_note_output_success_fields() {
        let out = SummarizeNoteOutput {
            summary: "A short TLDR.".to_string(),
            degraded: false,
        };
        assert_eq!(out.summary, "A short TLDR.");
        assert!(!out.degraded);
    }

    // ── Confidence ladder (TIN-1758) ──────────────────────────────────────────

    fn approx(a: f32, b: f32) -> bool {
        (a - b).abs() < 1e-6
    }

    #[test]
    fn band_cut_points() {
        assert_eq!(band(0.97), "settled");
        assert_eq!(band(0.85), "settled"); // inclusive lower bound
        assert_eq!(band(0.84), "likely");
        assert_eq!(band(0.55), "likely"); // inclusive lower bound
        assert_eq!(band(0.30), "unsure");
        assert_eq!(band(0.0), "unsure");
    }

    #[test]
    fn path_project_pins_folder_under_root() {
        let root = Path::new("/m");
        let got = path_project("/m/attic/note.md", root, &known());
        assert_eq!(got, Some("attic".to_string()));
    }

    #[test]
    fn path_project_none_when_not_under_known_folder() {
        let root = Path::new("/m");
        // Directly in the root → no folder hint.
        assert_eq!(path_project("/m/loose.md", root, &known()), None);
        // Unknown folder → no hint.
        assert_eq!(path_project("/m/misc/x.md", root, &known()), None);
    }

    // ── compose_field: each rung of the ladder ────────────────────────────────

    #[test]
    fn compose_path_derived_is_097() {
        let fc = compose_field(Some("attic"), "studio", Some(("understory", 0.9)));
        assert_eq!(fc.value, "attic");
        assert!(approx(fc.confidence, 0.97), "path-derived wins at 0.97: {}", fc.confidence);
        assert_eq!(fc.source, "path");
    }

    #[test]
    fn compose_rule_and_model_agree_is_095() {
        let fc = compose_field(None, "feedback", Some(("feedback", 0.6)));
        assert_eq!(fc.value, "feedback");
        assert!(approx(fc.confidence, 0.95), "agreement bump to 0.95: {}", fc.confidence);
        assert_eq!(fc.source, "agree");
    }

    #[test]
    fn compose_rule_and_model_disagree_is_030() {
        let fc = compose_field(None, "feedback", Some(("reference", 0.9)));
        // Keeps the rule value, but marks it unsure.
        assert_eq!(fc.value, "feedback");
        assert!(approx(fc.confidence, 0.30), "disagreement drops to 0.30: {}", fc.confidence);
        assert_eq!(fc.source, "none");
    }

    #[test]
    fn compose_rule_only_is_080() {
        let fc = compose_field(None, "studio", None);
        assert_eq!(fc.value, "studio");
        assert!(approx(fc.confidence, 0.80), "rule-only at 0.80: {}", fc.confidence);
        assert_eq!(fc.source, "rules");
    }

    #[test]
    fn compose_model_only_is_capped_at_075() {
        // Model returns a high score, but LLM-only is capped at 0.75.
        let fc = compose_field(None, "", Some(("reference", 0.95)));
        assert_eq!(fc.value, "reference");
        assert!(approx(fc.confidence, 0.75), "LLM-only capped at 0.75: {}", fc.confidence);
        assert_eq!(fc.source, "model");
        // A lower model score passes through uncapped.
        let low = compose_field(None, "", Some(("user", 0.4)));
        assert!(approx(low.confidence, 0.4), "model score below cap passes through: {}", low.confidence);
    }

    #[test]
    fn compose_nothing_matched_is_030_empty() {
        let fc = compose_field(None, "", None);
        assert!(fc.value.is_empty());
        assert!(approx(fc.confidence, 0.30), "nothing matched is 0.30: {}", fc.confidence);
        assert_eq!(fc.source, "none");
    }

    // ── build_result: overall = min, file-date, missing-field selection ───────

    fn rule_suggestion(type_: &str, projects: Vec<&str>) -> Suggestion {
        Suggestion {
            name: "n".into(),
            title: "N".into(),
            type_: type_.into(),
            projects: projects.into_iter().map(|s| s.into()).collect(),
            tags: vec![],
            created: String::new(),
            status: "active".into(),
            summary: None,
        }
    }

    #[test]
    fn build_result_overall_is_minimum_across_fields() {
        // type: rule-only (0.80); projects: path-derived (0.97); created: file-date (0.90).
        // Overall must be the MINIMUM = 0.80.
        let rules = rule_suggestion("feedback", vec!["studio"]);
        let missing = vec!["type".to_string(), "projects".to_string(), "created".to_string()];
        let res = build_result(
            "/m/attic/x.md",
            &rules,
            Some("attic"),
            "2026-06-20",
            &missing,
            None,
            None,
            true,
        );
        assert!(approx(res.fields["type"].confidence, 0.80));
        assert!(approx(res.fields["projects"].confidence, 0.97));
        assert!(approx(res.fields["created"].confidence, 0.90));
        assert!(approx(res.overall, 0.80), "overall is the min: {}", res.overall);
        assert_eq!(band(res.overall), "likely");
        // Path-derived project overrides the rule's project.
        assert_eq!(res.suggestion.projects, vec!["attic".to_string()]);
        assert_eq!(res.suggestion.created, "2026-06-20");
        assert!(res.degraded, "no model → degraded");
    }

    #[test]
    fn build_result_full_frontmatter_overall_is_one() {
        // Nothing missing → no fields → overall defaults to 1.0 (settled).
        let rules = rule_suggestion("project", vec!["studio"]);
        let res = build_result("/m/studio/x.md", &rules, Some("studio"), "2026-06-20", &[], None, None, false);
        assert!(res.fields.is_empty());
        assert!(approx(res.overall, 1.0), "no missing fields → 1.0: {}", res.overall);
        assert_eq!(band(res.overall), "settled");
    }

    #[test]
    fn build_result_uses_model_reply_for_ambiguous_type() {
        // Rule type "project" (the weak default), model says reference @0.9.
        // No path hint, no rule project. Model-only type capped at 0.75.
        let rules = rule_suggestion("project", vec![]);
        let missing = vec!["type".to_string()];
        let reply = "TYPE: reference 0.9\nPROJECT: NONE 0.0";
        let res = build_result("/m/x.md", &rules, None, "", &missing, Some(reply), None, false);
        // project rule "project" disagrees with model "reference" → 0.30, keeps rule value.
        assert_eq!(res.fields["type"].value, "project");
        assert!(approx(res.fields["type"].confidence, 0.30));
    }

    #[test]
    fn parse_model_reply_extracts_value_and_score() {
        let (t, p) = parse_model_reply("TYPE: feedback 0.82\nPROJECT: attic 0.7");
        assert_eq!(t.value, "feedback");
        assert!(approx(t.score, 0.82));
        assert_eq!(p.value, "attic");
        assert!(approx(p.score, 0.7));
    }

    #[test]
    fn parse_model_reply_treats_none_as_empty() {
        let (_t, p) = parse_model_reply("TYPE: project 0.5\nPROJECT: NONE 0.0");
        assert!(p.value.is_empty(), "NONE maps to empty value");
    }

    #[test]
    fn needs_model_skips_path_certain_and_strong_rules() {
        // type "feedback" (not the default) + path-pinned project → no model needed.
        let rules = rule_suggestion("feedback", vec!["studio"]);
        let missing = vec!["type".to_string(), "projects".to_string(), "created".to_string()];
        assert!(!needs_model(&missing, &rules, Some("attic")), "path + strong rules need no model");
    }

    #[test]
    fn needs_model_when_type_defaulted_or_project_ambiguous() {
        // Defaulted type → model wanted.
        let defaulted = rule_suggestion("project", vec!["studio"]);
        assert!(needs_model(&["type".to_string()], &defaulted, Some("studio")));
        // Ambiguous project (zero matches, no path) → model wanted.
        let no_proj = rule_suggestion("feedback", vec![]);
        assert!(needs_model(&["projects".to_string()], &no_proj, None));
    }

    // ── apply_one: body-preserving write + audit row ──────────────────────────

    #[test]
    fn apply_one_is_body_preserving_and_records_audit_row() {
        use std::io::Write;
        let dir = std::env::temp_dir().join(format!("fm-apply-{}", std::process::id()));
        let _ = fs::create_dir_all(&dir);
        let path = dir.join("note.md");
        {
            let mut f = fs::File::create(&path).unwrap();
            write!(f, "# Real Title\n\nThe body must survive verbatim.").unwrap();
        }

        let conn = rusqlite::Connection::open_in_memory().unwrap();
        crate::memory_audit::ensure_schema(&conn).unwrap();

        let input = ApplySuggestionInput {
            path: path.to_string_lossy().to_string(),
            suggestion: rule_suggestion_full(),
            actor_id: "llama3.1:8b".into(),
        };
        apply_one(&conn, &input).expect("apply succeeds");

        let written = fs::read_to_string(&path).unwrap();
        assert!(written.starts_with("---\n"), "frontmatter prepended");
        assert!(written.contains("type: feedback"), "suggested type written");
        assert!(written.trim_end().ends_with("The body must survive verbatim."), "body preserved");

        let hist = crate::memory_audit::history_for(&conn, &input.path).unwrap();
        assert_eq!(hist.len(), 1, "one audit row recorded");
        assert_eq!(hist[0].actor_type, "agent");
        assert_eq!(hist[0].actor_id, "llama3.1:8b");
        assert_eq!(hist[0].change_summary, "filled type, project, created");

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn apply_one_actor_defaults_to_rules_when_blank() {
        let dir = std::env::temp_dir().join(format!("fm-apply-rules-{}", std::process::id()));
        let _ = fs::create_dir_all(&dir);
        let path = dir.join("note.md");
        fs::write(&path, "# T\n\nBody.").unwrap();

        let conn = rusqlite::Connection::open_in_memory().unwrap();
        crate::memory_audit::ensure_schema(&conn).unwrap();

        let input = ApplySuggestionInput {
            path: path.to_string_lossy().to_string(),
            suggestion: rule_suggestion_full(),
            actor_id: String::new(),
        };
        apply_one(&conn, &input).unwrap();
        let hist = crate::memory_audit::history_for(&conn, &input.path).unwrap();
        assert_eq!(hist[0].actor_id, "rules", "blank actor → recorded as rules (degraded)");

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn apply_one_does_not_reindex_so_bulk_reindexes_once() {
        // Contract: apply_one performs NO index rebuild — the bulk command does a
        // single rebuild after the whole loop. We prove apply_one is self-contained
        // (write + audit row only) by running it against a connection that has ONLY
        // the audit schema (no search index tables). If apply_one tried to reindex,
        // it would need the search schema and fail; it succeeds, so it does not.
        let dir = std::env::temp_dir().join(format!("fm-bulk-{}", std::process::id()));
        let _ = fs::create_dir_all(&dir);
        let conn = rusqlite::Connection::open_in_memory().unwrap();
        crate::memory_audit::ensure_schema(&conn).unwrap();

        for i in 0..3 {
            let path = dir.join(format!("n{i}.md"));
            fs::write(&path, format!("# N{i}\n\nBody {i} stays.")).unwrap();
            let input = ApplySuggestionInput {
                path: path.to_string_lossy().to_string(),
                suggestion: rule_suggestion_full(),
                actor_id: "rules".into(),
            };
            apply_one(&conn, &input).expect("apply_one needs no search schema");
            assert!(
                fs::read_to_string(&path).unwrap().contains(&format!("Body {i} stays.")),
                "body {i} preserved",
            );
        }
        let _ = fs::remove_dir_all(&dir);
    }

    fn rule_suggestion_full() -> Suggestion {
        Suggestion {
            name: "note".into(),
            title: "Note".into(),
            type_: "feedback".into(),
            projects: vec!["studio".into()],
            tags: vec![],
            created: "2026-06-20".into(),
            status: "active".into(),
            summary: None,
        }
    }
}
